// Auto-generated. Do not edit!

// Updated: Mon Feb 19 17:02:59 2024

// (in-package tf2_msgs.msg)


// ignore_for_file: type=lint
import 'dart:convert';
import 'package:buffer/buffer.dart';
import 'package:dartros_msgutils/msg_utils.dart';

//-----------------------------------------------------------

class LookupTransformFeedback extends RosMessage<LookupTransformFeedback> {
  static LookupTransformFeedback $prototype = LookupTransformFeedback();
  LookupTransformFeedback();

  @override
  LookupTransformFeedback call() => LookupTransformFeedback();

  void serialize(ByteDataWriter writer) {
    // Serializes a message object of type LookupTransformFeedback
  }

  @override
  LookupTransformFeedback deserialize(ByteDataReader reader) {
    //deserializes a message object of type LookupTransformFeedback
    final data = LookupTransformFeedback();
    return data;
  }

  int getMessageSize() {
    return 0;
  }

  @override
  String get fullType {
    // Returns string type for a message object
    return 'tf2_msgs/LookupTransformFeedback';
  }

  @override
  String get md5sum {
    //Returns md5sum for a message object
    return 'd41d8cd98f00b204e9800998ecf8427e';
  }

  @override
  String get messageDefinition {
    // Returns full string definition for message
    return '''# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======


''';
  }

}

